### ISSUE TITLE
Build broken on windows

### ISSUE THREAD

**Issue by MatthieuDartiailh** [MacPython/enaml-wheels#1]
The build appear broken on windows with a non-sensical error message about being unable to find ply, but the same work on Linux. @matthew-brett can you make sense of this ?

**Comment by matthew-brett** [comment]
Yes, it's because the Windows install line doesn't allow installing dependencies.  I'm trying some fixes now.

**Comment by MatthieuDartiailh** [comment]
Thanks I would not have suspected this.

**Comment by matthew-brett** [comment]
enaml now functioning as expected, I believe - (but has QT failures) : https://ci.appveyor.com/project/matthew-brett/enaml-wheels/build/1.0.7

**Comment by MatthieuDartiailh** [comment]
Thanks @matthew-brett looks like there are some issues with the zip tests, I will handle it thanks for your help.

**Comment by MatthieuDartiailh** [comment]
I just fixed the broken tests but once again I get weird messages about missing dependencies @matthew-brett .

**Comment by MatthieuDartiailh** [comment]
Sorry for the noise I missed your commits on master.
