### ISSUE TITLE
PyQt segfault 

### ISSUE THREAD

**Issue by MatthieuDartiailh** [MacPython/enaml-wheels#2]
PyQt started to leads to segfault on Travis, for reasons I do not understand. I managed to fix it in https://github.com/nucleic/enaml/pull/343 in particular by adding this from the spyder-ide project:

```yaml
  # Avoid annoying focus problems when running tests
  # See discussion in e.g. https://github.com/spyder-ide/spyder/pull/6132
  - sudo apt-get -qq update
  - sudo apt-get install -y matchbox-window-manager xterm libxkbcommon-x11-0
  - matchbox-window-manager&
  - sleep 5
```

I am wondering if I can apply the same fix to this repo @matthew-brett . I am asking since I am not sure how this would interfere with multi-build. Also if you have a better solution for this I am interested.

**Comment by MatthieuDartiailh** [comment]
Applying this requires sudo which is not available in the container...

**Comment by matthew-brett** [comment]
`sudo` isn't available in the container, no, but all commands are super-user permissions by default - so just knocking `sudo` off the command should work.

**Comment by MatthieuDartiailh** [comment]
`apt-get` is not available on the image... any other suggestion about how I could get those added bits that allows to fix the tests.

**Comment by matthew-brett** [comment]
No - the image is based on CentOS - and a very old version.  You could try installing those things via yum, but - are they needed at run-time?  Will the wheel segfault if they are not installed, for the user?

**Comment by matthew-brett** [comment]
Sorry - the package manager for CentOS is yum ...

**Comment by MatthieuDartiailh** [comment]
This is not necessary for the build in itself, but without it the testing of the package is quite minimal. We could bypass testing on linux and test with pyqt only on Mac and windows.

**Comment by matthew-brett** [comment]
Yes, sure, but I was wondering what would happen to users installing the wheel on Linux; are they going to get segfaults without these packages?

**Comment by MatthieuDartiailh** [comment]
I don't think so. I tested on a recent Manjaro install and I could not reproduce the segfault (which is only related to pyqt wheels, conda packages do not segfault on Travis). It may be related to the fact that we do not have no real display.

**Comment by matthew-brett** [comment]
Any way of telling Qt that, via environment variables?

**Comment by MatthieuDartiailh** [comment]
In theory xvfb should make everything work but without the added packages it segfaults. I did no go yet through setting up a docker image to test locally and identify the actual root cause of the segfault. I spent a good part of my week-end looking for a solution and when I found that the magic apt-get lines in spyder I did not look much further.

**Comment by MatthieuDartiailh** [comment]
In Travis, activating xvfb is done through the xvfb services, for your image I have no idea how that would work but pytest-xvfb is supposed to take care of everything (if xvfb is installed obviously).

**Comment by matthew-brett** [comment]
Ah - sorry - the *test* image is Ubuntu trusty.  It does have `sudo` and `apt-get`, and can do the `apt-get` commands above.   Those command would need to go in the `run_tests` function in `config.sh`.  Having said that, running in a docker container now, I get:

```
root@5230697bb4e4:/# matchbox-window-manager&
[1] 593
root@5230697bb4e4:/# matchbox: can't open display! check your DISPLAY variable.
```

**Comment by MatthieuDartiailh** [comment]
You may need to have the xvfb service running for this to work. As I mentioned in Travis, this is done by enabling it in the service section. But it can also be done manually (I was using the following before Travis introduced xvfb service:
```
- export DISPLAY=:99.0
- /sbin/start-stop-daemon --start --quiet --pidfile /tmp/custom_xvfb_99.pid --make-pidfile --background --exec /usr/bin/Xvfb -- :99 -screen 0 1400x900x24 -ac +extension GLX +render
```)

**Comment by matthew-brett** [comment]
OK - then is it obvious what changes to make in `config.sh`? and `.travis.yml`?

**Comment by MatthieuDartiailh** [comment]
I will try yes. I was a bit confused by the build/test image separation, hopefully it will work through a couple of iterations.

**Comment by matthew-brett** [comment]
You'll need a Linux-specific conditional in `run_tests`, as in:

```
if [ -z "$IS_OSX" ]; then  # Running on Linux
    sudo apt-get whatever etc
fi
```

**Comment by MatthieuDartiailh** [comment]
Thanks ! I suspected as much but I started testing without actually.

**Comment by MatthieuDartiailh** [comment]
Interestingly xvfb refuses to start as a service (while it works here https://travis-ci.org/nucleic/enaml/jobs/514133015) I guess one difference is that I do not require sudo in my travis setup. I guess I will try to start it manually.

**Comment by MatthieuDartiailh** [comment]
And I use xenial, so I will try that next I guess.

**Comment by MatthieuDartiailh** [comment]
I think I am confused again: the test image is not the Travis one, correct ? I though it was for a moment.

I do not know why but I cannot start xvfb on your trusty image using any of the command suggested here https://docs.travis-ci.com/user/gui-and-headless-browsers/. On Travis to get the service working I had to use xenial but even when it was not starting properly matchbox seemed happy which magically fixes the segfault. I tried setting just the DISPLAY env var but it does not seem to work. Can I access your docker test image to try to debug this locally ? Also by curiosity what don't you use the Travis environment for testing after the build (just wondering because it naively looks easier) ?

**Comment by matthew-brett** [comment]
Definitely easier to test on the Travis image, but there is lots of stuff on the Travis image, and I wanted to test on a bare image, to check it works with nearly the minimal requirements.  Also, I wanted an equivalent 32-bit image; I don't think these are available for Travis.

Here's me starting up the test image:

```
docker pull matthewbrett/trusty:64 
docker run -ti --rm matthewbrett/trusty:64 /bin/bash
```

**Comment by MatthieuDartiailh** [comment]
Makes sense. I will try to find out how to start xvfb on your image.

**Comment by MatthieuDartiailh** [comment]
Ok so I believe I found how to install and run xvfb (https://medium.com/@griggheo/running-headless-selenium-webdriver-tests-in-docker-containers-342fdbabf756) but to do so I need to copy a file from the Travis the enaml-wheels repo to the docker image (xvfb.init). I cannot figure out how to do so. I see that you are calling files in the located in the repo from the docker so I guess it is possible, but I cannot figure out how to do so. Could you help me with that ?

**Comment by matthew-brett** [comment]
The repository gets mounted at `/io` inside the docker container - is that what you mean?

**Comment by MatthieuDartiailh** [comment]
Yes that was what I was looking for. Now when I don't get a crash because apt-get get stuck (half the builds) the build stops with no error message. I will have to try to investigate locally again. Thanks for your support.

**Comment by MatthieuDartiailh** [comment]
I really cannot wrap my head around this one. I believe it does not matter that much (in particular now that tests cover the C-extension and do not need Qt), so I am just going to skip using Qt on linux, osx and Windows should be enough.
